apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

patches:
  - target:
      kind: IPAddressPool
      name: default
    patch: |
      - op: add
        path: /spec/addresses
        value:
          - 10.219.2.0/24
